# Generated by Django 3.1.7 on 2021-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTypeDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('dist_type',
                 models.CharField(choices=[('pop', 'pop')], editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.ForeignKey(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingDonations',
            fields=[
                ('donation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      serialize=False, to='blood.donation')),
                ('units', models.IntegerField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
            ],
            options={
                'db_table': 'blood_outstanding_donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationBloodTypeDistribution',
            fields=[
                ('bloodtypedistribution_ptr', models.OneToOneField(auto_created=True,
                                                                   on_delete=django.db.models.deletion.CASCADE,
                                                                   parent_link=True,
                                                                   primary_key=True,
                                                                   serialize=False,
                                                                   to='blood.bloodtypedistribution')),
            ],
            bases=('blood.bloodtypedistribution',),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('request_blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('units', models.IntegerField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='blood.donation')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.issuerequest')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='blood.patient'),
        ),
        migrations.CreateModel(
            name='SingleRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('units', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.patient')),
            ],
            bases=('blood.issuerequest',),
        ),
        migrations.CreateModel(
            name='MCIRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('units', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.bloodtypedistribution')),
            ],
            bases=('blood.issuerequest',),
        ),
        migrations.CreateModel(
            name='PopulationBloodTypePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.populationbloodtypedistribution')),
            ],
            options={
                'unique_together': {('distribution_id', 'blood_type')},
            },
        ),
        migrations.RunSQL("""
    CREATE VIEW blood_outstanding_donations AS
    SELECT bd.id as donation_id, bd.units - IFNULL(SUM(bi.units),0) as units, bp.blood_type
    FROM blood_donation bd
    JOIN blood_patient bp on bd.donor_id = bp.id
    LEFT JOIN blood_issue bi on bd.id = bi.donation_id
    GROUP BY bd.id, bp.blood_type
    HAVING bd.units > IFNULL(SUM(bi.units),0)
""")
    ]
