# Generated by Django 3.1.7 on 2021-03-17 11:18

from django.db import migrations, models, transaction
import django.db.models.deletion

from blood.blood_types import CAN_DONATE, HIGH_PRIORITY_DAYS, MAX_BLOOD_AGE_DAYS, \
    POPULATION_BLOOD_TYPE_DISTRIBUTION


@transaction.atomic
def add_israel(apps, _schema_editor):
    dist = apps.get_model('blood', 'PopulationBloodTypeDistribution')

    israel = dist(name="Israel", dist_type=POPULATION_BLOOD_TYPE_DISTRIBUTION)
    israel.save()

    percentage = apps.get_model('blood', 'PopulationBloodTypePercentage')

    for btype, per in [
        ("O+", 32.0),
        ("A+", 34.0),
        ("B+", 17.0),
        ("AB+", 7.0),
        ("O-", 3.0),
        ("A-", 4.0),
        ("B-", 2.0),
        ("AB-", 1.0)
    ]:
        percentage(
            distribution=israel,
            blood_type=btype,
            percentage=per
        ).save()


@transaction.atomic
def add_ranks(apps, _schema_editor):
    rank = apps.get_model("blood", "BloodRank")

    for donor_type, recipient_types in CAN_DONATE.items():
        rank(blood_type=donor_type, rank=len(recipient_types)).save()


_OUTSTANDING_DONATIONS = f"""
CREATE VIEW blood_outstanding_donations AS
SELECT 
    bd.id as donation_id, 
    bd.units - IFNULL(SUM(bi.units),0) as units, 
    bp.blood_type, 
    bd.donation_date
FROM 
    blood_donation bd
    JOIN blood_patient bp on bd.donor_id = bp.id
    JOIN blood_rank br on bp.blood_type = br.blood_type
    LEFT JOIN blood_issue bi on bd.id = bi.donation_id
WHERE julianday('now') - julianday(bd.donation_date) < {MAX_BLOOD_AGE_DAYS}
GROUP BY bd.id, bp.blood_type
HAVING bd.units > IFNULL(SUM(bi.units),0)
ORDER BY 
    julianday('now') - julianday(bd.donation_date) > {HIGH_PRIORITY_DAYS}, 
    br.rank
"""

_OUTSTANDING_DONATIONS_MCI = f"""
CREATE VIEW blood_outstanding_donations_mci AS
SELECT 
    bd.id as donation_id, 
    bd.units - IFNULL(SUM(bi.units),0) as units, 
    bp.blood_type, 
    bd.donation_date
FROM 
    blood_donation bd
    JOIN blood_patient bp on bd.donor_id = bp.id
    JOIN blood_rank br on bp.blood_type = br.blood_type
    LEFT JOIN blood_issue bi on bd.id = bi.donation_id
WHERE julianday('now') - julianday(bd.donation_date) < {MAX_BLOOD_AGE_DAYS}
GROUP BY bd.id, bp.blood_type
HAVING bd.units > IFNULL(SUM(bi.units),0)
ORDER BY 
    julianday('now') - julianday(bd.donation_date) > {HIGH_PRIORITY_DAYS}, 
    br.rank DESC
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRank',
            fields=[
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10,
                    primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'blood_rank',
            },
        ),
        migrations.CreateModel(
            name='BloodTypeDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('dist_type',
                 models.CharField(choices=[('pop', 'pop')], editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('smokes', models.BooleanField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingDonations',
            fields=[
                ('donation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      serialize=False, to='blood.donation')),
                ('units', models.IntegerField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('donation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'blood_outstanding_donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutstandingDonationsMCI',
            fields=[
                ('donation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      serialize=False, to='blood.donation')),
                ('units', models.IntegerField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('donation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'blood_outstanding_donations_mci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationBloodTypeDistribution',
            fields=[
                ('bloodtypedistribution_ptr', models.OneToOneField(auto_created=True,
                                                                   on_delete=django.db.models.deletion.CASCADE,
                                                                   parent_link=True,
                                                                   primary_key=True,
                                                                   serialize=False,
                                                                   to='blood.bloodtypedistribution')),
            ],
            bases=('blood.bloodtypedistribution',),
        ),
        migrations.CreateModel(
            name='RejectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('units', models.IntegerField()),
                ('reject',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.reject')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('request_blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('units', models.IntegerField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='blood.donation')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.issuerequest')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='blood.patient'),
        ),
        migrations.CreateModel(
            name='SingleRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('units', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.patient')),
            ],
            bases=('blood.issuerequest',),
        ),
        migrations.CreateModel(
            name='MCIRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('units', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.bloodtypedistribution')),
            ],
            options={
                'verbose_name': 'MCI Request',
            },
            bases=('blood.issuerequest',),
        ),
        migrations.CreateModel(
            name='PopulationBloodTypePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.populationbloodtypedistribution')),
            ],
            options={
                'unique_together': {('distribution_id', 'blood_type')},
            },
        ),
        migrations.RunPython(add_israel),
        migrations.RunPython(add_ranks),
        migrations.RunSQL(_OUTSTANDING_DONATIONS),
        migrations.RunSQL(_OUTSTANDING_DONATIONS_MCI)
    ]
