# Generated by Django 3.1.7 on 2021-05-01 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'permissions': [
                ('can_collect', 'Can collect donations'),
                ('can_request_single', 'Can request single donations'),
                ('can_request_mci', 'Can request multiple donations')
            ]},
        ),
    ]
