# Generated by Django 3.1.7 on 2021-03-08 21:00

from django.db import migrations, transaction


@transaction.atomic
def add_israel(apps, _schema_editor):
    dist = apps.get_model('blood', 'PopulationBloodTypeDistribution')

    israel, _ = dist.objects.get_or_create(name="Israel")

    percentage = apps.get_model('blood', 'PopulationBloodTypePercentage')

    for btype, per in [
        ("O+", 32.0),
        ("A+", 34.0),
        ("B+", 17.0),
        ("AB+", 7.0),
        ("O-", 3.0),
        ("A-", 4.0),
        ("B-", 2.0),
        ("AB-", 1.0)
    ]:
        percentage.objects.get_or_create(
            distribution=israel,
            blood_type=btype,
            percentage=per
        )


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_israel),
    ]
