# Generated by Django 3.1.7 on 2021-03-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('units', models.IntegerField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='blood.donation')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.issuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='SingleRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='blood.patient')),
            ],
            bases=('blood.issuerequest',),
        ),
    ]
