# Generated by Django 3.1.7 on 2021-05-01 10:06

from django.db import migrations, transaction


@transaction.atomic
def add_groups(apps, _schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    donation_ct = ContentType.objects.get(app_label='blood', model='donation')

    def add_permissions(group: Group, *codes: str):
        for code in codes:
            perm, created = Permission.objects.get_or_create(content_type=donation_ct,
                                                             codename=code)

            if created:
                perm.save()

            group.permissions.add(perm)

        group.save()

    group_producer = Group(name="producer")
    group_producer.save()

    add_permissions(group_producer, "can_collect")

    group_consumer = Group(name="consumer")
    group_consumer.save()

    add_permissions(group_consumer, "can_request_single", "can_request_mci")


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0002_add_permissions'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
