# Generated by Django 3.1.7 on 2021-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0002_issue_issuerequest_singlerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerequest',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
