# Generated by Django 3.1.7 on 2021-03-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0002_add_israel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RejectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('units', models.IntegerField()),
                ('reject',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.reject')),
            ],
        ),
    ]
