# Generated by Django 3.1.7 on 2021-03-03 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0003_singlerequest_units'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE VIEW blood_outstanding_donations AS
SELECT bd.id as donation_id, bd.units - IFNULL(SUM(bi.units),0) as units, bp.blood_type
FROM blood_donation bd
JOIN blood_patient bp on bd.donor_id = bp.id
LEFT JOIN blood_issue bi on bd.id = bi.donation_id
GROUP BY bd.id, bp.blood_type
HAVING bd.units > IFNULL(SUM(bi.units),0)
        """)
    ]
