# Generated by Django 3.1.7 on 2021-03-09 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0003_reject_rejecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
