# Generated by Django 3.1.7 on 2021-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0004_issuerequest_request_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcirequest',
            options={'verbose_name': 'MCI Request'},
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smokes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
