# Generated by Django 3.1.7 on 2021-03-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blood', '0004_outstandingdonations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingDonations',
            fields=[
                ('donation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      serialize=False, to='blood.donation')),
                ('units', models.IntegerField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
            ],
            options={
                'db_table': 'blood_outstanding_donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodTypeDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('content_type', models.ForeignKey(editable=False, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationBloodTypeDistribution',
            fields=[
                ('bloodtypedistribution_ptr', models.OneToOneField(auto_created=True,
                                                                   on_delete=django.db.models.deletion.CASCADE,
                                                                   parent_link=True,
                                                                   primary_key=True,
                                                                   serialize=False,
                                                                   to='blood.bloodtypedistribution')),
            ],
            bases=('blood.bloodtypedistribution',),
        ),
        migrations.CreateModel(
            name='MCIRequest',
            fields=[
                ('issuerequest_ptr', models.OneToOneField(auto_created=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          parent_link=True, primary_key=True,
                                                          serialize=False,
                                                          to='blood.issuerequest')),
                ('units', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.bloodtypedistribution')),
            ],
            bases=('blood.issuerequest',),
        ),
        migrations.CreateModel(
            name='PopulationBloodTypePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='blood.populationbloodtypedistribution')),
            ],
            options={
                'unique_together': {('distribution_id', 'blood_type')},
            },
        ),
    ]
