# Generated by Django 3.1.7 on 2021-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blood',
         '0005_bloodtypedistribution_mcirequest_outstandingdonations_populationbloodtypedistribution_populationbloo'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='request_blood_type',
            field=models.CharField(
                choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                         ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='O-', max_length=10),
            preserve_default=False,
        ),
    ]
