# Generated by Django 3.1.7 on 2021-03-16 16:28

from django.db import migrations, models
import django.db.models.deletion

BLOOD_RANK = [
    ("O-", 8),
    ("O+", 4),
    ("A-", 3),
    ("A+", 2),
    ("B-", 4),
    ("B+", 2),
    ("AB-", 2),
    ("AB+", 1)
]

MAX_BLOOD_AGE_DAYS = 30
HIGH_PRIORITY_DAYS = 20


class Migration(migrations.Migration):
    dependencies = [
        ('blood', '0005_auto_20210316_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRank',
            fields=[
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10,
                    primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'blood_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutstandingDonationsMCI',
            fields=[
                ('donation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      serialize=False, to='blood.donation')),
                ('units', models.IntegerField()),
                ('blood_type', models.CharField(
                    choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'),
                             ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=10)),
                ('donation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'blood_outstanding_donations_mci',
                'managed': False,
            },
        ),

        migrations.RunSQL("DROP TABLE IF EXISTS blood_rank"),
        migrations.RunSQL("CREATE TABLE blood_rank(blood_type TEXT PRIMARY KEY , rank INT)"),

        migrations.RunSQL(sql=list(map(
            lambda pair: ("INSERT INTO blood_rank VALUES (%s,%s)", pair),
            BLOOD_RANK
        ))),

        migrations.RunSQL("DROP VIEW IF EXISTS blood_outstanding_donations"),
        migrations.RunSQL(f"""
    CREATE VIEW blood_outstanding_donations AS
    SELECT 
        bd.id as donation_id, 
        bd.units - IFNULL(SUM(bi.units),0) as units, 
        bp.blood_type, 
        bd.donation_date
    FROM 
        blood_donation bd
        JOIN blood_patient bp on bd.donor_id = bp.id
        JOIN blood_rank br on bp.blood_type = br.blood_type
        LEFT JOIN blood_issue bi on bd.id = bi.donation_id
    WHERE julianday('now') - julianday(bd.donation_date) < {MAX_BLOOD_AGE_DAYS}
    GROUP BY bd.id, bp.blood_type
    HAVING bd.units > IFNULL(SUM(bi.units),0)
    ORDER BY 
        julianday('now') - julianday(bd.donation_date) > {HIGH_PRIORITY_DAYS}, 
        br.rank
"""),

        migrations.RunSQL("DROP VIEW IF EXISTS blood_outstanding_donations_mci"),
        migrations.RunSQL(f"""
        CREATE VIEW blood_outstanding_donations_mci AS
        SELECT 
            bd.id as donation_id, 
            bd.units - IFNULL(SUM(bi.units),0) as units, 
            bp.blood_type, 
            bd.donation_date
        FROM 
            blood_donation bd
            JOIN blood_patient bp on bd.donor_id = bp.id
            JOIN blood_rank br on bp.blood_type = br.blood_type
            LEFT JOIN blood_issue bi on bd.id = bi.donation_id
        WHERE julianday('now') - julianday(bd.donation_date) < {MAX_BLOOD_AGE_DAYS}
        GROUP BY bd.id, bp.blood_type
        HAVING bd.units > IFNULL(SUM(bi.units),0)
        ORDER BY 
            julianday('now') - julianday(bd.donation_date) > {HIGH_PRIORITY_DAYS}, 
            br.rank DESC
""")
    ]
