# Generated by Django 3.1.7 on 2021-03-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blood', '0006_issue_request_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
        ),
    ]
